### ISSUE TITLE
Problems accessing web app

### ISSUE THREAD

**Issue by chacinelias** [robert-rc2i/ptq-client-webapp#44] opened 2023-05-27 00:24 UTC
**Describe the bug**
Browser says:
TypeError: Cannot read properties of undefined (reading 'split')

**To Reproduce**
I followed the instructions in the readme

**Expected behavior**
I expected the web app to appear in the browser

**Screenshots**
![Image 5-26-23 at 5 19 PM](https://github.com/robert-rc2i/ptq-client-webapp/assets/34133119/41982714-ab37-4acd-901b-38c22fa53727)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS (Pianoteq and server computer), Mac OSX (client with browser)
 - I tried Chrome, Firefox and Safari on iPhone

**Comment by robert-rc2i** [comment] 2023-05-28 01:01
Hi @chacinelias 

Can you tell me what version of Pianoteq you are using? 

I am going to look at it tomorrow when I get back home.  Maybe something changed with Pianoteq parameters with the newer version of 8.

Cheers

**Comment by robert-rc2i** [comment] 2023-05-29 01:45
Hi @chacinelias ,

I have tried the application with Pianoteq 8.0.8 and it works fine.

Pls le the know what version of Pianoteq you are using . 

Thx

**Comment by robert-rc2i** [comment] 2023-06-13 13:52
Closing as I cannot reproduce and no answer from the OP.

**Closed by robert-rc2i** 2023-06-13 13:52 UTC
Labels: Investigating

**Comment by robert-rc2i** [comment] 2023-11-10 13:06
Hi @chacinelias ,

The issue is most probably caused by the fact that you have Pianoteq Stage.  This project now support the Stage version of Pianoteq.  You can test it out using the AWS web url on the root page of this project or locally install it.

Regards.
